name: $name
version: $version
description: A Skript addon that allows you to create and manage packet-based scoreboards easily.
author: _tud

website: https://github.com/UnderscoreTud/skript-scoreboards
api-version: 1.13

main: ${group}.SkriptScoreboards
softdepend: [Skript]
